//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDbaseFirst3.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        [Display  ( Name ="First Name")]
        public string Fname { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Salary { get; set; }
        public string City { get; set; }
        [Display(Name = "Payment Type")]
        public string PaymentType { get; set; }
    }
}
